---
- name: my test playbook
  hosts: all
  become: true
  tasks:
    - name: web package install
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: apache web package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copy a file from source
      copy:
        src: /home/ansadmin/playbook/index.html
        dest: /var/www/html/
...
